# Generated by Django 4.1.7 on 2023-05-18 03:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_alter_subscriptions_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
